name: zoni_ui_widgetbook
description: Widgetbook for Zoni UI components
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.18.0
  widgetbook_annotation: ^3.9.0
  zoni_ui:
    path: ../

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.1.0

flutter:
  uses-material-design: true
